<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>brick</artifactId>
        <groupId>tech.gjsl</groupId>
        <version>${qdata.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>brick-api-ds-api</module>
        <module>brick-api-ds-biz</module>
    </modules>

    <packaging>pom</packaging>

    <artifactId>brick-api-ds</artifactId>

    <description>
        brick-api-ds模块
    </description>
</project>
