payment:
  alipay:
    # 应用ID
    appId: xxxxx
    # 应用私钥
    appPrivateKey: xxxxx
    # 支付宝公钥
    alipayPublicKey: xxxxx
    # 回调接口
    notifyUrl: xxxxx
    # 重定向回来路径
    returnUrl: xxxxx
    # 沙箱环境支付网地址 正式环境：openapi.alipay.com
    gatewayHost: xxxxx
    # 沙箱环境支付网地址 正式环境：https://openapi.alipay.com/gateway.do
    gatewayUrl: xxxxx
  wechat:
    # 应用ID
    appId: XXXXXX
    # 应用私钥
    appPrivateKey: XXXXXX
    # 支付宝公钥
    alipayPublicKey: XXXXXX
    # 回调接口
    notifyUrl:  http://bxbunc.natappfree.cc/alipay/notify
