<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>tech.gjsl</groupId>
        <artifactId>brick</artifactId>
        <version>${qdata.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>brick-config</module>
        <module>brick-websocket</module>
        <module>brick-mybatis</module>
        <module>brick-redis</module>
        <module>brick-quartz</module>
        <module>brick-security</module>
        <module>brick-generator</module>
        <module>brick-common</module>
        <module>brick-file</module>
        <module>brick-pay</module>
        <module>brick-auth</module>
    </modules>
    <packaging>pom</packaging>

    <artifactId>brick-framework</artifactId>

    <description>
        brick-framework模块
    </description>

</project>
